### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by myjsqmail** [zfl9/tls-proxy#2]
按照README文档的步骤，始终无法建立连接，client端一直报错：
[root@vmarch log]# journalctl -afu tls-client.service
-- Logs begin at Mon 2018-09-24 23:22:11 CST. --
Oct 22 22:35:18 vmarch sh[361]: 2018-10-22 22:35:18 INF: [udp] connecting to abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 ERR: [udp] openssl error: (336151568) sslv3 alert handshake failure
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] closed connect: abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] connecting to abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 ERR: [udp] openssl error: (336151568) sslv3 alert handshake failure
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] closed connect: abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] connecting to abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 ERR: [udp] openssl error: (336151568) sslv3 alert handshake failure
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] closed connect: abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] connecting to abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 ERR: [udp] openssl error: (336151568) sslv3 alert handshake failure
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] closed connect: abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] connecting to abc.com:443
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 ERR: [udp] openssl error: (336151568) sslv3 alert handshake failure
Oct 22 22:35:19 vmarch sh[361]: 2018-10-22 22:35:19 INF: [udp] closed connect: abc.com:443

client端curl到server是可以拿到页面的：
[root@vmarch log]# curl -v https://abc.com
* Rebuilt URL to: https://abc.com/
*   Trying 150.5.16.62...
* TCP_NODELAY set
* Connected to abc.com (150.5.16.62) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=abc.com
*  start date: Sep 27 14:00:55 2018 GMT
*  expire date: Dec 26 14:00:55 2018 GMT
*  subjectAltName: host "abc.com" matched cert's "abc.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55aa27247cf0)
> GET / HTTP/2
> Host: abc.com
> User-Agent: curl/7.61.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx
< date: Mon, 22 Oct 2018 15:31:29 GMT
< content-type: text/html
< content-length: 128
< last-modified: Mon, 22 Oct 2018 15:31:10 GMT
< etag: "5bcded3e-80"
< accept-ranges: bytes
< 
<!DOCTYPE html>
<html>
    <head>
        <title>Basic Web Page</title>
    </head>
    <body>
Hello World!
    </body>
</html>
* Connection #0 to host abc.com left intact

tls-client的启动脚本：
[root@vmarch log]# cat /etc/systemd/system/tls-client.service 
[Unit]
Description=tls-client
Requires=network.target network-online.target
After=network.target network-online.target

[Service]
Type=simple
ExecStart=/bin/sh -c "/usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/cert.pem -P /tls-proxy -H $'kou_ling: er_sha\r\n'"
Restart=always

[Install]
WantedBy=multi-user.target

server端nginx的配置:
server
    {
        listen 80;
        #listen [::]:80;
        server_name www.abc.com abc.com;
        return 301 https://$server_name$request_uri;
    }

server
    {
        listen 443 ssl http2;
        #listen [::]:443 ssl http2;
        server_name www.abc.com abc.com;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/www.abc.com/;
        ssl on;
        ssl_certificate /usr/local/caddy/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/abc.com/abc.com.crt;
        ssl_certificate_key /usr/local/caddy/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/abc.com/abc.com.key;
        ssl_session_timeout 5m;
        ssl_session_tickets on;
        resolver 8.8.8.8;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";
        ssl_session_cache builtin:1000 shared:SSL:10m;
        # openssl dhparam -out /usr/local/nginx/conf/ssl/dhparam.pem 2048
        ssl_dhparam /usr/local/nginx/conf/ssl/dhparam.pem;

        include rewrite/none.conf;
        #error_page   404   /404.html;

        # Deny access to PHP files in specific directory
        #location ~ /(wp-content|uploads|wp-includes|images)/.*\.php$ { deny all; }

        include enable-php.conf;

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /.well-known {
            allow all;
        }

        location ~ /\.
        {
            deny all;
        }

        location /tls-proxy {
            if ($kou_ling != 'er_sha') {
                return 404;
            }
            proxy_http_version 1.1;
            proxy_read_timeout 3650d;
            proxy_send_timeout 3650d;
            proxy_connect_timeout 3s;
            proxy_pass http://127.0.0.1:60080;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Upgrade $http_upgrade;
        }
        access_log off;
    }

tls-server的启动脚本:
root@150-95-186-62:/etc/systemd/system# cat tls-server.service 
[Unit]
Description=tls-server
Requires=network.target
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/tls-server -j2
Restart=always

[Install]
WantedBy=multi-user.target

感觉像是client端一直在用sslv3去握手，但是nginx已经禁用了sslv3，
已经倒腾两天了，希望zfl9给个指点，多谢啦。

**Comment by myjsqmail** [comment]
CAfile: /etc/ssl/certs/ca-certificates.crt
启动脚本中的 -c /etc/ssl/certs/ca-certificates.crt 换成这个也是同样的错误

**Comment by zfl9** [comment]
这个问题我稍后会修改一下 tls-client，以支持 `ECDHE-ECDSA-AES*` 加密套件。

**Comment by myjsqmail** [comment]
确实如您说的这样，我重新pull后编译，可以正常连接了，
但是如果您最初设计是考虑到安全或者性能的话，您还是将他们去掉吧，我修改nginx的设置，
这个问题是我没有注意到ssl_ciphers 的参数设定，问题在我。

另外，希望您能加入广告过滤的功能。针对指定的url列表，返回403或者直接关闭连接，多谢您
