### ISSUE TITLE
HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by myjsqmail** [zfl9/tls-proxy#3]
```
[Unit]
Description=tls-client
Requires=network.target network-online.target
After=network.target network-online.target

[Service]
Type=simple
ExecStart=/bin/sh -c "/usr/local/bin/tls-client -j2 -s www.example.com -c /etc/ssl/cert.pem -P /tls-proxy -H $'Some-Header: some_header_value\r\n'"
Restart=always

[Install]
WantedBy=multi-user.target
```

zfl9您好，关于tls-client启动脚本中http header的设置，经过测试发现兼容问题。
在archlinux系统中按照这个脚本启动，sh会自动把$符号去掉变成：
`45914 ?        Ssl    0:00 /usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/cert.pem -P /tls-proxy -H Some-Header: some_header_value? `
而在ubuntu16.04系统中启动，就会变成这样：
`23643 ?        Sl     0:00 /usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/certs/ca-certificates.crt -P /tls-proxy -H $Some-Header: some_header_value? `
tls-server端的nginx就会返回404，导致无法连接。
另外在archlinux中去掉$符号也是可以连接的，感觉这个$没什么用处。

所以建议您修改一下。

**Comment by zfl9** [comment]
你去掉这个 `$''` 也能用？你的 nignx 配置可以看一下吗

**Comment by zfl9** [comment]
我也是 archlinux，但是没有出现过你所描述的问题，我尝试将 `$''` 去掉，会出现 bad response。

**Comment by zfl9** [comment]
不要以 `ps -ef | grep tls-client` 的输出为准，它其实是显示问题，如果你想验证你的想法，你可以开一个 shell，执行 service 里面的命令，就知道哪个是正确，那个是错误的。

**Comment by myjsqmail** [comment]
nginx的配置
`        location /tls-proxy {
            if ($http_some_header != 'some_header_value') {
                return 404;
            }
            proxy_http_version 1.1;
            proxy_read_timeout 3650d;
            proxy_send_timeout 3650d;
            proxy_connect_timeout 3s;
            proxy_pass http://127.0.0.1:60080;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Upgrade $http_upgrade;
        }`

archlinux：
`[root@vmarch /]# ps -ef | grep tls-client
root        337      1  0 11:05 ?        00:00:00 /usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/cert.pem -P /tls-proxy -H Some-Header: some_header_value? 
root        356    353  0 11:06 pts/0    00:00:00 grep tls-client
[root@vmarch /]# journalctl -afu tls-client.service
-- Logs begin at Tue 2018-10-23 10:20:13 CST. --
Oct 24 11:05:30 vmarch systemd[1]: Started tls-client.
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [srv] thread nums: 2
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [srv] server host: abc.com
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [srv] server addr: 15.5.16.62:443
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [srv] tcp address: 127.0.0.1:60080
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [srv] udp address: 127.0.0.1:60080
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [udp] connecting to abc.com:443
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [udp] connected to abc.com:443
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [udp] send request to abc.com:443
Oct 24 11:05:30 vmarch sh[337]: 2018-10-24 11:05:30 INF: [udp] 192.168.1.107:56102 <-> abc.com:443
^C
[root@vmarch /]# cat /etc/systemd/system/tls-client.service 
[Unit]
Description=tls-client
Requires=network.target network-online.target
After=network.target network-online.target

[Service]
Type=simple
ExecStart=/bin/sh -c "/usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/cert.pem -P /tls-proxy -H 'Some-Header: some_header_value\r\n'"
Restart=always

[Install]
WantedBy=multi-user.target`

ubuntu16.04：
`chang@chang-virtual-machine:~$ ps -ef | grep tls-client
root      23828      1  0 11:11 ?        00:00:00 /bin/sh -c /usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/certs/ca-certificates.crt -P /tls-proxy -H 'Some-Header: some_header_value? '
root      23829  23828  0 11:11 ?        00:00:00 /usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/certs/ca-certificates.crt -P /tls-proxy -H Some-Header: some_header_value? 
chang     23838   3051  0 11:12 pts/2    00:00:00 grep --color=auto tls-client
chang@chang-virtual-machine:~$ journalctl -afu tls-client.service
-- Logs begin at 涓2018-10-24 10:52:08 CST. --
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [srv] thread nums: 2
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [srv] server host: abc.com
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [srv] server addr: 15.5.16.62:443
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [srv] tcp address: 127.0.0.1:60080
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [srv] udp address: 127.0.0.1:60080
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [udp] connecting to abc.com:443
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [udp] connected to abc.com:443
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [udp] send request to abc.com:443
10鏈24 11:11:15 chang-virtual-machine sh[23828]: 2018-10-24 11:11:15 INF: [udp] 192.168.1.254:14554 <-> abc.com:443
^C
chang@chang-virtual-machine:~$ sudo cat /etc/systemd/system/tls-client.service 
[Unit]
Description=tls-client
Requires=network.target network-online.target
After=network.target network-online.target

[Service]
Type=simple
ExecStart=/bin/sh -c "/usr/local/bin/tls-client -j2 -s abc.com -c /etc/ssl/certs/ca-certificates.crt -P /tls-proxy -H 'Some-Header: some_header_value\r\n'"
Restart=always

[Install]
WantedBy=multi-user.target`

**Comment by myjsqmail** [comment]
`[root@vmarch ~]# uname -a
Linux vmarch 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
[root@vmarch ~]# sh -c "echo 'hello\r\n'"
hello\r\n
[root@vmarch ~]# sh -c "echo $'hello\r\n'"
hello

[root@vmarch ~]# sh -c "echo $'hello\r\n'" | cat -A
hello^M$
$
[root@vmarch ~]# `

**Comment by zfl9** [comment]
我自己在 archlinux 上实际测试了一下，确实，去掉 `$` 可以正常使用，我想这应该是 systemd 自己会进行字符转义造成的，但是好像不去掉也没什么事吧？

**Comment by zfl9** [comment]
你加上 `$''` 就会导致 404 not found 吗？

**Comment by myjsqmail** [comment]
archlinux 去掉不去掉无所谓，没什么影响。
ubuntu16.04上，不去掉就会带着$发送给nginx，然后就404了

**Comment by zfl9** [comment]
OK，那看来加上这个 `$''` 转义外壳会导致兼容性问题，那我就去掉好了，谢谢反馈。

**Comment by myjsqmail** [comment]
不客气，请问这个软件下一步有什么计划呢？我强烈建议加入广告过滤功能

**Comment by zfl9** [comment]
暂时没有什么计划，因为最近也没啥时间折腾这个，广告过滤的话，有时间的时候会考虑的。

**Comment by myjsqmail** [comment]
好的，谢谢啦
