### ISSUE TITLE
ConnectionType和Connectiontype

### ISSUE THREAD

**Issue by myjsqmail** [zfl9/tls-proxy#4]
用nginx作为web server
nginx传给tls-server的header字段是ConnectionType
`Oct 24 17:32:06  tls-server[7984]: reqline=GET /tls-proxy HTTP/1.1
Oct 24 17:32:06  tls-server[7984]: reqline=Connection: Upgrade
Oct 24 17:32:06  tls-server[7984]: reqline=Upgrade: websocket
Oct 24 17:32:06  tls-server[7984]: reqline=Host: 127.0.0.1:60080
Oct 24 17:32:06  tls-server[7984]: reqline=Some-Header: some_header_value
Oct 24 17:32:06  tls-server[7984]: reqline=ConnectionType: udp
`
用caddy作为web server
caddy传的是Connectiontype
`Oct 24 17:34:48 tls-server[7984]: reqline=GET /tls-proxy HTTP/1.1
Oct 24 17:34:48 tls-server[7984]: reqline=Host: 127.0.0.1:60080
Oct 24 17:34:48 tls-server[7984]: reqline=User-Agent: Go-http-client/1.1
Oct 24 17:34:48 tls-server[7984]: reqline=Connection: Upgrade
Oct 24 17:34:48 tls-server[7984]: reqline=Connectiontype: udp
Oct 24 17:34:48 tls-server[7984]: reqline=Some-Header: some_header_value
Oct 24 17:34:48 tls-server[7984]: reqline=Upgrade: websocket
Oct 24 17:34:48 tls-server[7984]: reqline=X-Forwarded-For: 1.1.1.1
Oct 24 17:34:48 tls-server[7984]: reqline=Accept-Encoding: gzip
Oct 24 17:34:48 tls-server[7984]: reqline=
`
如果是Connectiontype那么tls-server.c的355行就不会匹配上，连接就被关闭了。

**Comment by zfl9** [comment]
所以，有什么问题吗？我只推荐使用 nginx，其他 web server 我不熟悉，也不感冒。

**Comment by myjsqmail** [comment]
没什么，只是caddy能帮我自动更新证书，所以选了他

**Comment by zfl9** [comment]
至于为什么 caddy 会将 `ConnectionType` 转换为 `Connectiontype` 我也不清楚，我觉得 nginx 配置好了之后挺好用的，而且 C 写的东西性能肯定比 Go 好
